displayOrder: 1
imagePath: /images/0217/mentions.png
videoUrl: https://www.youtube.com/e/0YutYJg6Tgw
title: @mention Others
description: > 
    <h4>Notify Other Users</h4>
    <p>@mentions are a great way to notify other users about content and conversations they should be involved 
    in. Best of all, they work just like Twitter and Facebook.</p> <p>&nbsp;</p>
    <h4>Receive Email Notifications</h4>
    <p>When you are mentioned you'll receive an email notification so you can jump right into Confluence and 
    never miss another conversation again.</p> <p>&nbsp;</p>
    <h4>Works in Pages, Blogs, &amp; Comments</h4>
    <p>Just type the '@' symbol and choose from a list of the users you follow, or start typing a user's name.</p>
