displayOrder: 2
imagePath: /images/0217/new-editor.png
videoUrl: https://www.youtube.com/e/P9-AKX9lSL8
title: Brand New Editor
description: >
    <h4>Brand New Look</h4>
    <p>Built for the needs of every user, a new streamlined interface maximizes your editing space so you 
    can create rich content with extraordinary speed and simplicity.</p> <p>&nbsp;</p>
    <h4>Autoformatting Magic</h4>
    <p>Type wiki markup and watch Confluence convert it on the fly. Formatted text, tables, symbols, emoticons 
    &ndash; it all works.</p> <p>&nbsp;</p>
    <h4>Visual Macros</h4>
    <p>Editing and working with macros is now much easier. Just like images and links, now you can click a 
    macro to perform common actions.</p> <p>&nbsp;</p>
    <p><a href="http://confluence.atlassian.com/x/JhIaDg">See our Quick Reference Guide for the Confluence 
    Editor &gt;&gt;</a></p>
