displayOrder: 3
imagePath: /images/0217/tables.png
videoUrl: https://www.youtube.com/e/ZL49lqH-6l8
title: Table & Image Editing
description: >
    <h4>Advanced Table Editing</h4>
    <p>
    <span>Insert new tables with drag-and-drop simplicity. Merge, split, highlight cells, and more.</span>
    </p> <p>&nbsp;</p>
    <h4>Copy &amp; Paste Images</h4>
    <p><span>Paste images from your clipboard directly into the editor when using Safari, Firefox, or 
    Chrome.</span></p> <p>&nbsp;</p>
    <h4>Resize &amp; Link Images</h4>
    <p><span>Enter a custom width for embedded images and link them to other content like pages, blogs, and 
    external sites.</span></p>
