Plugin:
    listeners: [XssListener]

    columns:
        name: 
            type: string
            extra:
                purify: plaintext
        class:
            type: string
            extra:
                purify: plaintext
        description: 
            type: string
            extra:
                purify: html
