Product:
    listeners: [IndexListener]

    columns:
        vendor:
            type: string(255)
            extra:
                notify: true
                logicalName: Vender
            comment: The name of the vendor who brands this product
        name:
            type: string(255)
            extra:
                notify: true
                logicalName: Name
            comment: Name of the product
        version:
            type: string(255)
            extra:
                notify: true
                logicalName: Version
            comment: Version of the product
        cpeName:
            type: string(255)
            unique: true
            extra:
                logicalName: CPE ID
                notify: true
            comment: The common platform enumeration (CPE) for this product, if known
    actAs:
        SoftDelete: true
