Product:
    listeners: [XssListener, IndexListener]
    
    columns:
        vendor:
            type: string(255)
            extra:
                purify: plaintext
                searchIndex: unstored
            comment: The name of the vendor who brands this product
        name:
            type: string(255)
            extra:
                purify: plaintext
                searchIndex: unstored
            comment: Name of the product
        version:
            type: string(255)
            extra:
                purify: plaintext
                searchIndex: keyword
            comment: Version of the product
        cpeName:
            type: string(255)
            extra:
                purify: plaintext
            comment: The common platform enumeration (CPE) for this product, if known
