########################################################################################################################
#
# Copyright (c) 2012 Endeavor Systems, Inc.
#
# This file is part of OpenFISMA.
#
# OpenFISMA is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# OpenFISMA is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY# without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OpenFISMA.  If not, see {@link http://www.gnu.org/licenses/}.
#
########################################################################################################################
#
# Configure file for building menu.
#
# Author:    Xue-Wei Tang<xue-wei.tang@endeavorsystems.com>
# Copyright: (c) Endeavor Systems, Inc. 2012 {@link http://www.endeavorsystems.com}
# License:   http://www.openfisma.org/content/license
#
########################################################################################################################

#
# Findings
#
FindingDashboard:
    url: /finding/dashboard
    breadcrumb-labels: Findings,Dashboard
    breadcrumb-links: no-link,no-link
FindingReportOverdueFinding:
    url: /finding/remediation/list?
    breadcrumb-labels: Findings,Reports,Overdue Findings,View
    breadcrumb-links: no-link,no-link,/finding/report/overdue/format/html,no-link
FindingList:
    url: /finding/remediation/list
    breadcrumb-labels: Findings,Search
    breadcrumb-links: no-link,no-link
FindingView:
    url: /finding/remediation/view
    breadcrumb-labels: Findings,Search,View
    breadcrumb-links: no-link,/finding/remediation/list,no-link
FindingCreate:
    url: /finding/remediation/create
    breadcrumb-labels: Findings,Create New Finding
    breadcrumb-links: no-link,no-link
FindingUpload:
    url: /finding/index/injection
    breadcrumb-labels: Findings,Upload Spreadsheet
    breadcrumb-links: no-link,no-link
FindingAdminWorkflow:
    url: /finding/workflow/view
    breadcrumb-labels: Findings,Administration,Workflow
    breadcrumb-links: no-link,no-link,no-link   
FindingAdminGeneral:
    url: /finding/config/general
    breadcrumb-labels: Findings,Administration,General
    breadcrumb-links: no-link,no-link,no-link
FindingAdminSourceView:
    url: /finding/source/view/id
    breadcrumb-labels: Findings,Administration,Sources,View
    breadcrumb-links: no-link,no-link,/finding/source/list,no-link
FindingAdminSource:
    url: /finding/source/list
    breadcrumb-labels: Findings,Administration,Sources
    breadcrumb-links: no-link,no-link,no-link
FindingReportFISMA:
    url: /finding/report/fisma
    breadcrumb-labels: Findings,Reports,OMB FISMA
    breadcrumb-links: no-link,no-link,no-link
FindingReportOverdue:
    url: /finding/report/overdue
    breadcrumb-labels: Findings,Reports,Overdue Findings
    breadcrumb-links: no-link,no-link,no-link
FindingReportPluginReport:
    url: /finding/report/plugin-report
    breadcrumb-labels: Findings,Reports,Plugin Reports,View
    breadcrumb-links: no-link,no-link,/finding/report/plugin,no-link            
FindingReportPlugin:
    url: /finding/report/plugin
    breadcrumb-labels: Findings,Reports,Plugin Reports
    breadcrumb-links: no-link,no-link,no-link    

#
# Vulnerabilities
#
VulnerabilityList:
    url: /vm/vulnerability/list
    breadcrumb-labels: Vulnerabilities,Search
    breadcrumb-links: no-link,no-link
VulnerabilityView:
    url: /vm/vulnerability/view/
    breadcrumb-labels: Vulnerabilities,Search,View
    breadcrumb-links: no-link,/vm/vulnerability/list,no-link
VulnerabilityUpload:
    url: /vm/vulnerability/plugin
    breadcrumb-labels: Vulnerabilities,Upload Scan Results
    breadcrumb-links: no-link,no-link
VulnerabilityAdminProductsView:
    url: /vm/product/view/id
    breadcrumb-labels: Vulnerabilities,Administration,Products,View
    breadcrumb-links: no-link,no-link,/vm/product/list,no-link
VulnerabilityAdminProductsCreate:
    url: /vm/product/create
    breadcrumb-labels: Vulnerabilities,Administration,Products,Create
    breadcrumb-links: no-link,no-link,/vm/product/list,no-link
VulnerabilityAdminProducts:
    url: /vm/product/list
    breadcrumb-labels: Vulnerabilities,Administration,Products
    breadcrumb-links: no-link,no-link,no-link
VulnerabilityAdminResolutionsView:
    url: /vm/vulnerability-resolution/view/id
    breadcrumb-labels: Vulnerabilities,Administration,Resolutions,View
    breadcrumb-links: no-link,no-link,/vm/vulnerability-resolution/list,no-link
VulnerabilityAdminResolutionsCreate:
    url: /vm/vulnerability-resolution/create
    breadcrumb-labels: Vulnerabilities,Administration,Resolutions,Create
    breadcrumb-links: no-link,no-link,/vm/vulnerability-resolution/list,no-link    
VulnerabilityAdminResolutions:
    url: /vm/vulnerability-resolution/list
    breadcrumb-labels: Vulnerabilities,Administration,Resolutions
    breadcrumb-links: no-link,no-link,no-link
VulnerabilityReportAggregated:
    url: /vm/vulnerability-report/risk/
    breadcrumb-labels: Vulnerabilities,Reports,Aggregated Risk
    breadcrumb-links: no-link,no-link,no-link    
VulnerabilityReportReopened:
    url: /vm/vulnerability-report/reopened/
    breadcrumb-labels: Vulnerabilities,Reports,Reopened Vulnerabilities
    breadcrumb-links: no-link,no-link,no-link    
VulnerabilityReportServices:
    url: /vm/vulnerability-report/vulnerable-service/
    breadcrumb-labels: Vulnerabilities,Reports,Vulnerable Services
    breadcrumb-links: no-link,no-link,no-link    
        
#
# Incidents
#
IncidentList:
    url: /incident/list
    breadcrumb-labels: Incidents,Search
    breadcrumb-links: no-link,no-link
IncidentView:
    url: /incident/view/
    breadcrumb-labels: Incidents,Search,View
    breadcrumb-links: no-link,/incident/list,no-link
IncidentReport:
    url: /incident/report
    breadcrumb-labels: Incidents,Report An Incident
    breadcrumb-links: no-link,no-link
IncidentDashboard:
    url: /incident-dashboard
    breadcrumb-labels: Incidents,Dashboard
    breadcrumb-links: no-link,no-link
IncidentAdminCategoriesView:
    url: /ir-category/view/id/
    breadcrumb-labels: Incidents,Administration,Categories,View
    breadcrumb-links: no-link,,no-link,/ir-category/list,no-link    
IncidentAdminCategoriesCreate:
    url: /ir-category/create
    breadcrumb-labels: Incidents,Administration,Categories,Create
    breadcrumb-links: no-link,,no-link,/ir-category/list,no-link    
IncidentAdminCategories:
    url: /ir-category/list
    breadcrumb-labels: Incidents,Administration,Categories
    breadcrumb-links: no-link,,no-link,no-link
IncidentAdminWorkflowsView:
    url: /ir-workflow/view/id
    breadcrumb-labels: Incidents,Administration,Workflows,View
    breadcrumb-links: no-link,,no-link,/ir-workflow/list,no-link
IncidentAdminWorkflowsCreate:
    url: /ir-workflow/create
    breadcrumb-labels: Incidents,Administration,Workflows,Create
    breadcrumb-links: no-link,,no-link,/ir-workflow/list,no-link
IncidentAdminWorkflows:
    url: /ir-workflow/list
    breadcrumb-labels: Incidents,Administration,Workflows
    breadcrumb-links: no-link,,no-link,no-link
IncidentReportOrganizations:
    url: /incident-report/organization/
    breadcrumb-labels: Incidents,Reports,Incident Organizations
    breadcrumb-links: no-link,,no-link,no-link       
IncidentReportCategories:
    url: /incident-report/category/
    breadcrumb-labels: Incidents,Reports,Incident Categories
    breadcrumb-links: no-link,,no-link,no-link     
IncidentReportHistory:
    url: /incident-report/history/
    breadcrumb-labels: Incidents,Reports,Incident History
    breadcrumb-links: no-link,,no-link,no-link       
            
#
# System Inventory
#
SystemAsset:
    url: /asset/list
    breadcrumb-labels: System Inventory,Assets
    breadcrumb-links: no-link,no-link
SystemAssetView:
    url: /asset/view/
    breadcrumb-labels: System Inventory,Assets,View
    breadcrumb-links: no-link,/asset/list,no-link
SystemAssetCreate:
    url: /asset/create
    breadcrumb-labels: System Inventory,Assets,Create
    breadcrumb-links: no-link,/asset/list,no-link
SystemAssetImport:
    url: /asset/import
    breadcrumb-labels: System Inventory,Assets,Import
    breadcrumb-links: no-link,/asset/list,no-link
SystemControl:
    url: /security-control/list
    breadcrumb-labels: System Inventory,Controls
    breadcrumb-links: no-link,no-link
SystemControlView:
    url: /security-control/view/id
    breadcrumb-labels: System Inventory,Controls,View
    breadcrumb-links: no-link,/security-control/list,no-link
SystemDocument:
    url: /system-document/list
    breadcrumb-labels: System Inventory,Documentation
    breadcrumb-links: no-link,no-link
SystemDocumentView:
    url: /system-document/view/
    breadcrumb-labels: System Inventory,Documentation,View
    breadcrumb-links: no-link,/system-document/list,no-link   
SystemOrganizationView:
    url: /organization/view/
    breadcrumb-labels: System Inventory,Organizations,View
    breadcrumb-links: no-link,/organization/list,no-link    
SystemOrganizationCreate:
    url: /organization/create
    breadcrumb-labels: System Inventory,Organizations,Create
    breadcrumb-links: no-link,/organization/list,no-link     
SystemOrganization:
    url: /organization/list
    breadcrumb-labels: System Inventory,Organizations
    breadcrumb-links: no-link,no-link
SystemInventoryView:
    url: /system/view/
    breadcrumb-labels: System Inventory,Systems,View
    breadcrumb-links: no-link,/system/list,no-link  
SystemInventoryCreate:
    url: /system/create
    breadcrumb-labels: System Inventory,Systems,Create
    breadcrumb-links: no-link,/system/list,no-link  
SystemInventory:
    url: /system/list
    breadcrumb-labels: System Inventory,Systems
    breadcrumb-links: no-link,no-link
SystemInventoryDashboard:
    url: /organization-dashboard
    breadcrumb-labels: System Inventory,Dashboard
    breadcrumb-links: no-link,no-link  
SystemAdminControlCatalog:
    url: /security-control-catalog/list
    breadcrumb-labels: System Inventory,Administration,Control Catalogs
    breadcrumb-links: no-link,no-link,no-link 
SystemAdminControlCatalogView:
    url: /security-control-catalog/view/
    breadcrumb-labels: System Inventory,Administration,Control Catalogs,View
    breadcrumb-links: no-link,no-link,/security-control-catalog/list,no-link    
SystemAdminDocumentTypeView:
    url: /document-type/view/
    breadcrumb-labels: System Inventory,Administration,Document Types,View
    breadcrumb-links: no-link,no-link,/document-type/list,no-link        
SystemAdminDocumentTypeCreate:
    url: /document-type/create
    breadcrumb-labels: System Inventory,Administration,Document Types,Create
    breadcrumb-links: no-link,no-link,/document-type/list,no-link            
SystemAdminDocumentType:
    url: /document-type/list
    breadcrumb-labels: System Inventory,Administration,Document Types
    breadcrumb-links: no-link,no-link,no-link 
SystemAdminIconManagement:
    url: /icon/manage
    breadcrumb-labels: System Inventory,Administration,Icon Management
    breadcrumb-links: no-link,no-link,no-link 
SystemAdminNetworkView:
    url: /network/view/
    breadcrumb-labels: System Inventory,Administration,Networks,View
    breadcrumb-links: no-link,no-link,/network/list,no-link        
SystemAdminNetworkCreate:
    url: /network/create
    breadcrumb-labels: System Inventory,Administration,Networks,Create
    breadcrumb-links: no-link,no-link,/network/list,no-link           
SystemAdminNetwork:
    url: /network/list
    breadcrumb-labels: System Inventory,Administration,Networks
    breadcrumb-links: no-link,no-link,no-link  
SystemAdminOrganizationTypeView:
    url: /organization-type/view/
    breadcrumb-labels: System Inventory,Administration,Organization Types,View
    breadcrumb-links: no-link,no-link,/organization-type/list,no-link    
SystemAdminOrganizationTypeCreate:
    url: /organization-type/create
    breadcrumb-labels: System Inventory,Administration,Organization Types,Create
    breadcrumb-links: no-link,no-link,/organization-type/list,no-link      
SystemAdminOrganizationType:
    url: /organization-type/list
    breadcrumb-labels: System Inventory,Administration,Organization Types
    breadcrumb-links: no-link,no-link,no-link    
SystemAdminSystemTypeView:
    url: /system-type/view/
    breadcrumb-labels: System Inventory,Administration,System Types,View
    breadcrumb-links: no-link,no-link,/system-type/list,no-link    
SystemAdminSystemTypeCreate:
    url: /system-type/create
    breadcrumb-labels: System Inventory,Administration,System Types,Create
    breadcrumb-links: no-link,no-link,/system-type/list,no-link    
SystemAdminSystemType:
    url: /system-type/list
    breadcrumb-labels: System Inventory,Administration,System Types
    breadcrumb-links: no-link,no-link,no-link    
SystemReportDocumentCompliance:
    url: /organization-report/documentation-compliance/
    breadcrumb-labels: System Inventory,Reports,Document Compliance
    breadcrumb-links: no-link,no-link,no-link
SystemReportPersonnel:
    url: /organization-report/personnel/
    breadcrumb-labels: System Inventory,Reports,Personnel
    breadcrumb-links: no-link,no-link,no-link
SystemReportPrivacy:
    url: /organization-report/privacy/
    breadcrumb-labels: System Inventory,Reports,Privacy
    breadcrumb-links: no-link,no-link,no-link
SystemReportSecurityAuthorizations:
    url: /organization-report/security-authorization/
    breadcrumb-labels: System Inventory,Reports,Security Authorizations
    breadcrumb-links: no-link,no-link,no-link

#
# Administration
#       
AdminSysConfigEmail:
    url: /config/email
    breadcrumb-labels: Administration,System Configuration,Email
    breadcrumb-links: no-link,no-link,no-link
AdminSysConfigPolicies:
    url: /config/general
    breadcrumb-labels: Administration,System Configuration,General Policies
    breadcrumb-links: no-link,no-link,no-link
AdminSysConfigLDAP:
    url: /config/list-ldap
    breadcrumb-labels: Administration,System Configuration,LDAP
    breadcrumb-links: no-link,no-link,no-link
AdminSysConfigLDAPEdit:
    url: /config/update-ldap/
    breadcrumb-labels: Administration,System Configuration,LDAP,Edit
    breadcrumb-links: no-link,no-link,/config/list-ldap,no-link
AdminSysConfigPasswordPolicy:
    url: /config/password
    breadcrumb-labels: Administration,System Configuration,Password Policy
    breadcrumb-links: no-link,no-link,no-link
AdminSysConfigPrivacyPolicy:
    url: /config/privacy
    breadcrumb-labels: Administration,System Configuration,Privacy Policy
    breadcrumb-links: no-link,no-link,no-link
AdminSysConfigContact:
    url: /config/contact
    breadcrumb-labels: Administration,System Configuration,Technical Contact
    breadcrumb-links: no-link,no-link,no-link
AdminUserManagementRoleView:
    url: /role/view/
    breadcrumb-labels: Administration,User Management,Roles,View
    breadcrumb-links: no-link,no-link,/role/list,no-link 
AdminUserManagementRoleCreate:
    url: /role/create
    breadcrumb-labels: Administration,User Management,Roles,Create
    breadcrumb-links: no-link,no-link,/role/list,no-link 
AdminUserManagementRole:
    url: /role/list
    breadcrumb-labels: Administration,User Management,Roles
    breadcrumb-links: no-link,no-link,no-link      
AdminUserManagementUserView:
    url: /user/view/
    breadcrumb-labels: Administration,User Management,Users,View
    breadcrumb-links: no-link,no-link,/user/list,no-link    
AdminUserManagementUserCreate:
    url: /user/create
    breadcrumb-labels: Administration,User Management,Users,Create
    breadcrumb-links: no-link,no-link,/user/list,no-link     
AdminUserManagementUser:
    url: /user/list
    breadcrumb-labels: Administration,User Management,Users
    breadcrumb-links: no-link,no-link,no-link    
AdminDiagnosticsSystemCache:
    url: /debug/apc-cache/type/system
    breadcrumb-labels: Administration,Diagnostics,APC System Cache
    breadcrumb-links: no-link,no-link,no-link    
AdminDiagnosticsUserCache:
    url: /debug/apc-cache/type/user
    breadcrumb-labels: Administration,Diagnostics,APC User Cache
    breadcrumb-links: no-link,no-link,no-link    
AdminDiagnosticsErrorLog:
    url: /debug/errorlog
    breadcrumb-labels: Administration,Diagnostics,Error Log
    breadcrumb-links: no-link,no-link,no-link    
AdminDiagnosticsPHPInfo:
    url: /debug/phpinfo
    breadcrumb-labels: Administration,Diagnostics,PHP Info
    breadcrumb-links: no-link,no-link,no-link    
AdminDiagnosticsPHPLog:
    url: /debug/phplog
    breadcrumb-labels: Administration,Diagnostics,PHP Log
    breadcrumb-links: no-link,no-link,no-link    
AdminDiagnosticsSearchTest:
    url: /config/search
    breadcrumb-labels: Administration,Diagnostics,Search Test
    breadcrumb-links: no-link,no-link,no-link   
    
#
# UserPreferences
#     
UserPreferencesChangePassword:
    url: /user/password
    breadcrumb-labels: User Preferences,Change Password
    breadcrumb-links: no-link,no-link 
UserPreferencesNotification:
    url: /user/notification
    breadcrumb-labels: User Preferences,E-mail Notifications
    breadcrumb-links: no-link,no-link 
UserPreferencesProfile:
    url: /user/profile
    breadcrumb-labels: User Preferences,My Profile
    breadcrumb-links: no-link,no-link 
UserPreferencesHomeURL:
    url: /user/preferences
    breadcrumb-labels: User Preferences,Preferences
    breadcrumb-links: no-link,no-link 
